name: Publish FreeSurfer image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - 'freesurfer/Dockerfile'
    - '.github/workflows/docker-freesurfer.yml'
env:
  IMAGE_ID: ghcr.io/maastrichtu-ids/jupyterlab:freesurfer
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file freesurfer/Dockerfile --tag $IMAGE_ID

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          docker push $IMAGE_ID
